modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${mod_license}"
clientSideOnly=true

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/dynamic_player_model/icon.png"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
