org.gradle.jvmargs=-Xmx1G -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
loader_version=0.19.3
loom_version=1.17.17
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.1
forge_version=65.1.3
forge_loader_version_range=[65,)
forge_version_range=[65.1.3,)
forgegradle_version=[7.0.17,8)
neoforge_version=26.2.0.75
neoforge_loader_version_range=[1,)
neoforge_version_range=[26.2.0.75,)
moddevgradle_version=2.0.146

mod_id=dynamic_player_model
mod_name=Dynamic Player Model
mod_description=Client-side visual player proportions and first-person hand transforms for Minecraft 26.2.
mod_authors=northwestcloudymac
mod_license=MIT
mod_version=1.0.7+26.2
maven_group=com.northwestcloudymac
archives_base_name=dynamic-player-model
