modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"
clientSideOnly=true

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
iconFile="assets/dynamic_player_model/icon.png"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[mixins]]
config="dynamic_player_model.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="viewmodel"
type="incompatible"
reason="Its first-person transforms overlap with Dynamic Player Model."
versionRange=""
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="scaleme"
type="incompatible"
reason="Its player scaling transforms overlap with Dynamic Player Model."
versionRange=""
ordering="NONE"
side="CLIENT"
